### ISSUE TITLE
Scrape data from am mysql database and store it in a solr index

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/etda#10]
In order to search data (#9)  we need a way to harvest data from the ETD systems (Graduate and Honors) and put that into a solr index for blacklight.

We will need to only harvest published papers.  We will need to match exiting information available to the users from the current system.

Search result:
![screen shot 2015-10-15 at 8 20 27 am](https://cloud.githubusercontent.com/assets/1599081/10513479/d1180880-7315-11e5-81b6-8de2c9de5c31.png)

show page:
![screen shot 2015-10-15 at 8 21 02 am](https://cloud.githubusercontent.com/assets/1599081/10513485/e382f5e8-7315-11e5-9428-655b8c4b5136.png)

**Comment by cam156** [comment]
We are assuming access via login, so that we can use a solr connector.

**Comment by DanCoughlin** [comment]
Not sure I understand "access via login" do you mean solr will log in to MySQL for access to data and index it?

**Comment by awead** [comment]
@DanCoughlin yes. It can access MySQL via JDBC. It just needs credentials. Ideally, a user with select only privs. to the database.
