### ISSUE TITLE
Implement the Catalog Search results view

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/etda#12]
We need to include similar items to what exists in the current search view: Author, Ttitle, Area of Honors, Keyword, Committee Members 

![screen shot 2015-10-15 at 8 20 27 am](https://cloud.githubusercontent.com/assets/1599081/10513580/9ccb7ff2-7316-11e5-91d5-0e46b62cb987.png)

There is likely some defined set for Graduate, and a different set for honors, so the fields should be configurable.

This is part of the Search Thesis User story. #9

**Comment by cam156** [comment]
In the blacklight configuration you can set up the clickable search for the key terms, or you can override the view.

**Comment by DanCoughlin** [comment]
These labels do change with partner (i.e. Area of Honors is only for Schreyer, it's called Program, I believe) for grad school.
