### ISSUE TITLE
Implement the Thesis Show page

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/etda#13]
Implement a show page that allows the user to see the metadata about the ETD and additionally download the the Thesis

![screen shot 2015-10-15 at 8 21 02 am](https://cloud.githubusercontent.com/assets/1599081/10514009/4ea3d7fe-7319-11e5-9f12-784ca39993f7.png)

This is part of the Search Thesis User Story #9

**Comment by DanCoughlin** [comment]
The "thing" to consider here is that a restricted theses has published metadata, just not a document. So metadata on a released thesis is always public, but not the actual file. Also the third permission for Penn State only (which only exists for Grad School) allows for metadata to be seen by anyone, but only downloaded by PSU authN users.

**Comment by jrpatterson** [comment]
Here are examples of each and how they appear currently:
psu only (restricted with web access credentials for download)
https://etdadev.libraries.psu.edu/paper/22614/
https://etdadev.libraries.psu.edu/paper/22081/
https://etdadev.libraries.psu.edu/paper/22553/

restricted:
https://etdadev.libraries.psu.edu/paper/7937/
https://etdadev.libraries.psu.edu/paper/10955/
https://etdadev.libraries.psu.edu/paper/6482/

**Comment by jrpatterson** [comment]
Honors also has a restricted class that corresponds to graduate restricted.  There is no psu only for Honors.
https://honorsdev.libraries.psu.edu/paper/25132/
https://honorsdev.libraries.psu.edu/paper/25400/
https://honorsdev.libraries.psu.edu/paper/25469/
