### ISSUE TITLE
Committee member failure

### ISSUE THREAD

**Issue by jrpatterson** [psu-stewardship/etda#136]
I was testing test case num 2 and I received this

The change you wanted was rejected.

Maybe you tried to change something you didn't have access to.

~ 4/14/11:10 AM 
![etd-case-2-failed](https://cloud.githubusercontent.com/assets/2422371/14533157/01b1fb1c-0232-11e6-889a-c27c8bc72727.png)

**Comment by jrpatterson** [comment]
The next time I did this it worked, but the first submission I used the same member on all fields, not sure if that is what did it.

**Comment by jrpatterson** [comment]
The original submission was left alone though I started a new one.

**Comment by cam156** [comment]
@jrpatterson Did you use the back button at all?  I have tried it on QA and locally using the back button, but did not get an error.  CSFR errors are usually related to using the back button to get to a form.

**Comment by jrpatterson** [comment]
@cam156  Unfortunately I did not use the back button here. I entered in committee members and hit submit.  Pressing submit caused the issue to happen.  

I watched this happen as well last week on the committee reports page, a user selected a few submissions and then pressed "export csv"  and in testing it was noted as occurring several times on that page.

The production log showed messages such as this at the problem times:
WARN -- : Can't verify CSRF token authenticity
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):

**Comment by jonibar** [comment]
I asked Steve whether he was using the back button and other questions about how the error occurred on the Committee Reports page and here was his response:

Joni,

Ok. I just tried again and it is working for me now.  I will let you know if 
I encounter the problem in the future.  Thank you.


Steven Chichester

Assistant Director of Graduate Enrollment Services

The Pennsylvania State University

The Graduate School

114 Kern Graduate Building

University Park, PA 16802

814-865-1834

**Comment by jrpatterson** [comment]
@cam156  @jonibar  It was Steve that I watched.

**Comment by jonibar** [comment]
haven't been able to reproduce
