### ISSUE TITLE
Allow code base to be configurable for both Honors and Graduate School

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/etda#15]
We have written the previous tickets for #9 with the screen shots from the Honors system.  Now we need to compare the Honors system with the Graduate System, and determine what additional configurations are needed

Search View:
<img width="990" alt="screen shot 2015-10-15 at 8 54 34 am" src="https://cloud.githubusercontent.com/assets/1599081/10514194/6df31452-731a-11e5-8c6e-fb23268c4b42.png">

Search Terms:

<img width="296" alt="screen shot 2015-10-15 at 8 55 18 am" src="https://cloud.githubusercontent.com/assets/1599081/10514229/953b5088-731a-11e5-99f3-90eb539cb356.png">

Show View:

<img width="912" alt="screen shot 2015-10-15 at 8 56 43 am" src="https://cloud.githubusercontent.com/assets/1599081/10514250/b64f7cea-731a-11e5-8471-499049affcb3.png">

**Comment by DanCoughlin** [comment]
To be clear, this interface is allowed to be improved upon. We were converting an old UI with the last upgrade and I think we have a bit more freedom now.

**Comment by cam156** [comment]
Show page: 
  * Honors does snot show email
  * "Area of Honors" vs "Graduate Program"
  * Honors does not show Date of Defense
  * "Thesis Supervisor" vs "Committee"
 
Search Listing:
  * "Area of Honors" vs "Graduate Program"
  * "Thesis Supervisor" vs "Committee"

**Comment by cam156** [comment]
https://github.com/psu-stewardship/etda/commit/abfcbd2d40b9a4cda4c94c82598f968f3b0ce164
