### ISSUE TITLE
Blank Download link on catalog page

### ISSUE THREAD

**Issue by jonibar** [psu-stewardship/etda#169]
Unauthenticated users see a blank download link on catalog page
![screen shot 2016-05-10 at 10 15 04 am](https://cloud.githubusercontent.com/assets/2422369/15149701/8fec6f96-1698-11e6-919b-6a3720570ad0.png)

**Comment by cam156** [comment]
@jonibar Since you are not logged in you do not have access to download the paper.  What would you like to see?

**Comment by jonibar** [comment]
@cam156 - I expected to see a link which would allow users to log in and display the document.  I attempted to get that working last week. Another option is a message instructing the user to log in.  The last option is to remove 'Download' but then PSU users don't know they can view the paper...so that's my least favorite.  Any ideas?

**Comment by cam156** [comment]
The code here: https://github.com/psu-stewardship/etda/blob/master/app/presenters/document_presenter.rb#L28-L35
Could be copied to here: https://github.com/psu-stewardship/etda/blob/master/app/helpers/blacklight_display_helper.rb#L22.

That would give you a similar link to what you get when you go to the show page.
