### ISSUE TITLE
Browse eTD

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/etda#38]
We need a browse page for ETDs.
![screen shot 2015-11-16 at 12 16 24 pm](https://cloud.githubusercontent.com/assets/1599081/11189048/e603f04c-8c5b-11e5-847d-4ee4f9d5b18c.png)

I saw some interesting browse pages at the blacklight summit showing pages of facets.  We could use the facet query from solr to get information.  Princeton in particular had a search capability in the facet pages.

**Comment by awead** [comment]
Would this effectively be all the documents in solr sorted by last name?

**Comment by cam156** [comment]
@awead yes, or by program

**Comment by cam156** [comment]
@awead I would be interested in stealing something from someone else though.    I did not have many notes, but I thought the browse in Princeton's blacklight was nifty.  Let me ping them...

**Comment by awead** [comment]
@cam156 sounds good! My own naive solution would be to just use /catalog with empty search parameters:
http://localhost:3000/catalog?utf8=%E2%9C%93&search_field=all_fields&q=
but there's probably a much more elegant solution.

**Comment by cam156** [comment]
@awead I did not get any response from Nikitas, but I did discuss with Dan the possibility of showing a list of facet values and allowing the user to click through those instead of a list of results sorted by name, or program.
