### ISSUE TITLE
Symbolically link the correct blacklight and solr.yml in Cap

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/etda#54]
rm blacklight.yml
ln -s /dlt/etda/config_qa/etda/honors_blanklight.yml blanklight.yml
ls -l
rm solr.yml
ln -s blanklight.yml solr.yml

**Comment by jrpatterson** [comment]
This is now complete: https://github.com/psu-stewardship/etda/commit/047ab083d4654c4fa681f27a369bbc8207ac6432
