### ISSUE TITLE
Restricted confirmation

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/etda#62]
When they click on a psu restricted theses have a window that pops up and says "hey please don't share this outside of penn state"

**Comment by cam156** [comment]
@mtribone This is the area where I think we could better indicate the availability of the paper before they click the link.  Possibly with an icon, or some other way.  Any thoughts you have on a good way to indicate restricted to PSU VS open would be appreciated.

**Comment by jonibar** [comment]
The current application uses this layout for papers restricted to PSU

**Comment by cam156** [comment]
@jonibar I'm not seeing a location, or image.

**Comment by jonibar** [comment]
![screen shot 2016-02-11 at 8 26 18 am](https://cloud.githubusercontent.com/assets/2422369/12980045/a55fbe54-d0a8-11e5-966e-4b6fe874286a.png)

**Comment by jonibar** [comment]
Ooops--attaching the image to email didn't work....

**Comment by mtribone** [comment]
So it does have an image...I'll walk through the system again and get a feel for it.
