### ISSUE TITLE
Create a search interface on top of graduate and honors dissertations

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/etda#9]
Allow a user to find an existing released Thesis from either Honors or the graduate school (in two separate systems) so that users can view existing Thesis on their topic or key term.

1) Scrape data from am mysql database and store it in a solr index
2) bring up a vanilla blacklight on top of the solr index
3) customize to include links to the ETD system, and appropriate facets
4) repeat 1-3 for the second database

**Comment by DanCoughlin** [comment]
I am assuming there will be full-text indexing here. Let me know if that is wrong.

**Comment by hectorcorrea** [comment]
I don't think full-text indexing explicitly for this story, but I don't think including it will change much for it. However, supporting full-text indexing will change the process to populate Solr. Perhaps we should update store #10 to indicate that we need to extract the text of the documents too.

**Comment by awead** [comment]
@hectorcorrea the default hydra/blacklight solr config copies all fields to a "full_text" field that's used for searching. We should be able to use the same config and have it work, provided our solr fields follow the same naming conventions... which, by the way, I think they should.
