### ISSUE TITLE
Author Submission Committee Members Page links & buttons (accessibility)

### ISSUE THREAD

**Issue by jonibar** [psu-stewardship/etda#98]
Change tabindex order on this page so that [remove] link is the last item of the group.

Change 'Return to Dashboard' to 'Save and Return to Dashboard' and change processing to do the same.

**Comment by cam156** [comment]
@jonibar Moving around the remove link to have it placed at the top, but read at the bottom is not working easily.  I can work on adding javascript to reposition the remove link, or we can make life simple and just move it to the bottom.  What do you think?

**Comment by jonibar** [comment]
I suggest simple and to move it to the bottom.  It works and committee members can be entered.  We can improve it next release.

**Comment by cam156** [comment]
@jonibar Thanks for the feedback!

**Comment by cam156** [comment]
fixed by #115
